### ISSUE TITLE
USER STORY: User Login Features

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#1]
As an **site user** I can **create and account, login and logout from an account** so that ** I can create recipes, comment and like**

### Acceptance Criteria:
- **Acceptance Criteria 1:** A user should be able to signup and create an account. 
- **Acceptance Criteria 2:** The user should be able to login in if they already have an account.
- **Acceptance Criteria 3:** The user should be able to logout from their account.

### Tasks
- [x] Download Allauth to manage registration.
- [x] Route the Allauth urls.
- [x] Download Allauth templates.
- [x] Extend and modify respective Allauth template for your use.
- [x] Add more details for user to add on the user instance upon signup.
