### ISSUE TITLE
USER STORY: Social Media Link

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#12]
As an **user/site viewer** I can **access site creators social media profiles** so that **I can find out more about the site creator or contact**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Social media link to the application authors Github and Linkedin should be present on the header or on the footer. 
- **Acceptance Criteria 2:** Links should open another tab.
- **Acceptance Criteria 3:** Links should lead to the correct address

### Tasks
- [x] Create link on the header or on the footer to the authors profiles.
- [x] Add FontAwesome logos to the link.
- [x] Add descriptive text to inform users of the link use.
