### ISSUE TITLE
USER STORY: Admin Recipe Management

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#13]
As an **admin** I can **manage recipes** so that **I can ensure the quality of the posted material**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Admin has a site where they can see posted recipes.
- **Acceptance Criteria 2:** Admin should be able to carry out all the CRUD activities on the recipe objects.
- **Acceptance Criteria 3:** Admin site should be accessible only to Admin.
- **Acceptance Criteria 4:** Admin should be able to filter and sort the recipes viewed.

### Tasks

- [x] Create admin account.
- [x] Create site for admin to interact with.
- [ ] Add a filters.
- [ ] Add a sorting method
