### ISSUE TITLE
USER STORY: My Profile

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#14]
As an **user** I can **view my user information** so that **have get more personalized experience from the application**

### Acceptance Criteria:
- **Acceptance Criteria 1:** User should be able to see their name and email address(if added).
- **Acceptance Criteria 2:** User profile should be accessible from the navigation menu for the user.
- **Acceptance Criteria 3:** User should be able to see a list recipes names they have liked.
- **Acceptance Criteria 4:** User should be able to see a list with comments stating the name of the recipe and first 50 characters of the comment they have made. 

### Tasks

- [ ] Extend user class and add methods that track recipes liked and comments made. 
- [ ] Add a template to for my profile. 
- [ ] Add class based views for compiling recipes liked information. 
- [ ] Add class based views for compiling comments made information. 
- [ ] Order the comments starting with most recent.
- [ ] Linking and commenting updates the user class.
