### ISSUE TITLE
USER STORY: Comment

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#2]
As a **user** I can **leave comments on a post** so that **I connect and discuss of the recipes with my fellow users**

### Acceptance Criteria:
- **Acceptance Criteria 1:** User can view comments.
- **Acceptance Criteria 2:** User can add comments to a recipe.
- **Acceptance Criteria 3:** Users name, date of comment and text are visible.
- **Acceptance Criteria 4:** The most recent comment will show on the top.

### Tasks

- [x] Create comment class.
- [x] Create view for commenting.
- [x] Route the view to the recipe post template.
- [x] On template create add comment form.
- [x] Add posted comments to the templates.
- [x] Order the comments starting with most recent.
- [x] Add  a number of comments on top of the all comments that updates when comment is added.
