### ISSUE TITLE
USER STORY: View Selection of Recipe

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#3]
As an **site viewer/user** I can **view a selection of recipes** so that **I can select the one I want to view**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Recipes should be listed on the home page.
- **Acceptance Criteria 2:** Each recipe should display the name of the image/placeholder image, recipe, date posted, description, Region and likes.
- **Acceptance Criteria 3:** Multiple recipes should fit on the front page and after maximum is reached pagination should be added.
- **Acceptance Criteria 4:** the whole recipe card should act as a link to the recipe view.

### Tasks

- [x] Create example instances.
- [x] Add cards on index template.
- [x] Add image, name, region, likes, description and date on the card.
- [x] Add pagination.
- [x] Test pagination.
