### ISSUE TITLE
USER STORY: Like a recipe

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#4]
As an **user** I can **like or unlike a recipe** so that **I can promote recipes I like**

### Acceptance Criteria:
- **Acceptance Criteria 1:** User should be able to like and unlike a recipe by clicking the heart icon. 
- **Acceptance Criteria 2:** User should be able to click the icon on the page with recipe cards and on the recipe page. 
- **Acceptance Criteria 3:** The like icon should change from outline to filled icon and the number of likes should go up.

### Tasks

- [x] Add like feature on the class based view that adds or removes user like. 
- [x] Route the view. 
- [x] Add the feature to the html.
