### ISSUE TITLE
USER STORY: View Comments

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#6]
As a **site viewer/user** I can **open a recipe* so that **I can read any comments**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Any visitor or logged in user can view comments.
- **Acceptance Criteria 2:** Comments appear on same page as the recipe.
- **Acceptance Criteria 2:** Comments should also detail the name and date.

### Tasks

- [x] Add comments on the same template as the recipe itself.
- [x] Organize comments so the most recent one is always on the top.
- [x] Name and date of the comment should be visible.
