### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/p4-recipe-book#7]
As a **site viewer/user** I can **easily navigate the site** so that **I can find what I need**

### Acceptance Criteria:
- **Acceptance Criteria 1:** Header has a navigation menu that is available on each page. 
- **Acceptance Criteria 2:** Recipes work as links to the recipe details. 
- **Acceptance Criteria 3:** CRUD functionalities have clear buttons everywhere. 

### Tasks
- [x] Add navigation  menu to the base.html
- [x] Add link to the Create functionality.
- [x] Add link to the Update functionality.
- [x] Add link to the Delete functionality.
- [x] Recipes displayed on the frontage lead to the actual recipes.
